services:
  - type: web
    name: math-simple
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: python manage.py migrate && python create_superuser.py && gunicorn seu_projeto.wsgi